# List available commands
default:
    @just --list

build:
    go build -o bin/az ./cmd/az
    go build -o bin/azd ./cmd/azd

run:
    go build -o bin/azd ./cmd/azd
    go run ./cmd/az

test:
    go test -v ./...

test-coverage:
    go test -coverprofile=coverage.out ./...
    go tool cover -html=coverage.out -o coverage.html

type-check:
    go build ./...

clean:
    rm -rf bin/ coverage.out coverage.html

install:
    go install ./cmd/az

lint:
    golangci-lint run ./...
