package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var ErrSpecMarkdownDrift = errors.New("spec markdown artifacts are out of date; run: az spec sync --target md")

type SpecMarkdownSyncFile struct {
	Path   string `json:"path"`
	Status string `json:"status"`
}

type SpecMarkdownSyncResult struct {
	Target  string                 `json:"target"`
	Mode    string                 `json:"mode"`
	Changed bool                   `json:"changed"`
	Files   []SpecMarkdownSyncFile `json:"files"`
}

type generatedSpecFile struct {
	Path    string
	Content string
}

func RunSpecMarkdownSync(repoDir string, check bool) (SpecMarkdownSyncResult, error) {
	files := generatedSpecFiles()
	result := SpecMarkdownSyncResult{
		Target: "md",
		Mode:   "apply",
		Files:  make([]SpecMarkdownSyncFile, 0, len(files)),
	}
	if check {
		result.Mode = "check"
	}

	for _, file := range files {
		absPath := filepath.Join(repoDir, filepath.FromSlash(file.Path))
		existing, err := os.ReadFile(absPath)
		exists := err == nil
		if err != nil && !os.IsNotExist(err) {
			return SpecMarkdownSyncResult{}, fmt.Errorf("read %s: %w", file.Path, err)
		}

		status := "ok"
		if !exists || string(existing) != file.Content {
			result.Changed = true
			if check {
				status = "drift"
			} else {
				if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
					return SpecMarkdownSyncResult{}, fmt.Errorf("create %s directory: %w", file.Path, err)
				}
				if err := os.WriteFile(absPath, []byte(file.Content), 0o644); err != nil {
					return SpecMarkdownSyncResult{}, fmt.Errorf("write %s: %w", file.Path, err)
				}
				if exists {
					status = "updated"
				} else {
					status = "created"
				}
			}
		}
		result.Files = append(result.Files, SpecMarkdownSyncFile{Path: file.Path, Status: status})
	}

	if check && result.Changed {
		return result, ErrSpecMarkdownDrift
	}
	return result, nil
}

func generatedSpecFiles() []generatedSpecFile {
	return []generatedSpecFile{
		{Path: "docs/spec/README.md", Content: renderSpecDocsIndex()},
		{Path: "docs/spec/az-spec-phase1.md", Content: renderSpecPhase1Markdown()},
	}
}

func renderSpecDocsIndex() string {
	lines := []string{
		"# Spec Docs",
		"",
		"This directory is generated by `az spec sync --target md`.",
		"Treat these Markdown files as the spec source of truth when this directory is present.",
		"",
		"## Files",
		"",
		"- [az-spec-phase1.md](az-spec-phase1.md): deterministic phase-1 CLI grammar and current Go runtime implementation status.",
	}
	return strings.Join(lines, "\n") + "\n"
}

func renderSpecPhase1Markdown() string {
	lines := []string{
		"# az spec Phase 1",
		"",
		"Generated by `az spec sync --target md`.",
		"",
		"## Current Runtime Status",
		"",
		"- CLI grammar is restored for `req`, `link`, `read`, `lint`, `parity`, and `sync --target md`.",
		"- `az spec sync --target md` is implemented in the Go CLI layer and keeps this directory deterministic.",
		"- `req`, `link`, `read`, `lint`, and `parity` currently validate syntax and return a consistent not-implemented error until daemon-backed spec contracts land.",
		"",
		"## Requirement Commands",
		"",
		"1. `az spec req list [--json] [--issue <issue-id>] [--status <open|accepted|superseded>] [--id <req-id> ...] [--ids a,b,c]`",
		"2. `az spec req get --id <req-id> [--json]`",
		"3. `az spec req create --id <req-id> --title <text> [--description <text>] [--issue <issue-id>] [--json]`",
		"4. `az spec req update --id <req-id> [--title <text>] [--description <text>] [--status <open|accepted|superseded>] [--json]`",
		"5. `az spec req delete --id <req-id> --confirm [--json]`",
		"",
		"## Link Commands",
		"",
		"1. `az spec link list [--json] [--issue <issue-id>] [--req <req-id>] [--id <link-id> ...] [--ids a,b,c]`",
		"2. `az spec link add --issue <issue-id> --req <req-id> [--role <implements|verifies|relates>] [--note <text>] [--json]`",
		"3. `az spec link remove --issue <issue-id> --req <req-id> [--json]`",
		"",
		"## Read, Lint, Parity, and Sync",
		"",
		"1. `az spec read [--json] [--issue <issue-id>] [--req <req-id>]`",
		"2. `az spec lint [--json] [--strict]`",
		"3. `az spec parity [--json] [--fail-on-out]`",
		"4. `az spec sync --target md [--check] [--json]`",
		"",
		"## Determinism Rules",
		"",
		"- Flags stay before positional arguments.",
		"- Repeated selector flags preserve caller order after first-occurrence deduplication.",
		"- `--ids` comma lists trim whitespace and drop empty tokens.",
		"- Disabled spec workflows fail fast with remediation: `az config set spec.enabled true`.",
		"- `az spec sync --target md --check` reports drift without mutating files.",
	}
	return strings.Join(lines, "\n") + "\n"
}
