package main

import (
	"strings"
	"testing"
)

func TestMaybePrintCommandHelpIgnoresNonHelpArgs(t *testing.T) {
	if maybePrintCommandHelp([]string{"issue", "get", "csi"}) {
		t.Fatal("maybePrintCommandHelp returned true for non-help command")
	}
	if maybePrintCommandHelp([]string{"definitely-not-a-command", "--help"}) {
		t.Fatal("maybePrintCommandHelp returned true for unknown help path")
	}
}

func TestMaybePrintCommandHelpCoversRoutedCommandSurface(t *testing.T) {
	paths := [][]string{
		{},
		{"help"},
		{"version"},
		{"session"},
		{"session", "start"},
		{"session", "attach"},
		{"session", "stop"},
		{"session", "kill"},
		{"session", "status"},
		{"session", "capture"},
		{"session", "restart-all"},
		{"session", "resolve-conflict"},
		{"start"},
		{"attach"},
		{"stop"},
		{"kill"},
		{"status"},
		{"branch"},
		{"branch", "merge"},
		{"branch", "merge-to-base"},
		{"branch", "agent-merge"},
		{"worktree"},
		{"worktree", "create"},
		{"operation"},
		{"operation", "get"},
		{"operation", "list"},
		{"operation", "queue"},
		{"operation", "logs"},
		{"operation", "cancel"},
		{"export"},
		{"log"},
		{"config"},
		{"config", "set"},
		{"spec"},
		{"spec", "req"},
		{"spec", "req", "list"},
		{"spec", "req", "get"},
		{"spec", "req", "create"},
		{"spec", "req", "update"},
		{"spec", "req", "delete"},
		{"spec", "link"},
		{"spec", "link", "list"},
		{"spec", "link", "add"},
		{"spec", "link", "remove"},
		{"spec", "read"},
		{"spec", "pack"},
		{"spec", "graph"},
		{"spec", "slice"},
		{"spec", "slice", "gate"},
		{"spec", "lint"},
		{"spec", "parity"},
		{"decision"},
		{"decision", "list"},
		{"decision", "get"},
		{"decision", "record"},
		{"decision", "update"},
		{"decision", "delete"},
		{"decision", "revisit"},
		{"decision", "sync"},
		{"decision", "import"},
		{"decision", "link"},
		{"decision", "link", "list"},
		{"decision", "link", "add"},
		{"decision", "link", "remove"},
		{"learn"},
		{"learn", "add"},
		{"learn", "recall"},
		{"learn", "show"},
		{"learn", "review"},
		{"learn", "stale"},
		{"learn", "demote"},
		{"learn", "promote"},
		{"learn", "retire"},
		{"learn", "relate"},
		{"learn", "supersede"},
		{"learn", "doctor"},
		{"learn", "gc"},
		{"sync"},
		{"githooks"},
		{"githooks", "install"},
		{"githooks", "update"},
		{"githooks", "run"},
		{"githooks", "notify"},
		{"githooks", "hook"},
		{"gate"},
		{"dev"},
		{"dev", "gate"},
		{"dev", "start"},
		{"dev", "stop"},
		{"dev", "restart"},
		{"dev", "status"},
		{"dev", "list"},
		{"project"},
		{"project", "list"},
		{"project", "add"},
		{"project", "remove"},
		{"project", "scripts"},
		{"project", "scripts", "status"},
		{"impl"},
		{"impl", "list"},
		{"impl", "delete"},
		{"impl", "migrate"},
		{"ai"},
		{"ai", "install"},
		{"ai", "status"},
		{"ai", "uninstall"},
		{"ai", "migrate"},
		{"ai", "hook"},
		{"ai", "hook", "run"},
		{"tmux"},
		{"tmux", "selector"},
		{"tmux", "install-selector"},
		{"tmux", "uninstall-selector"},
		{"prime"},
		{"issue"},
		{"issue", "list"},
		{"issue", "search"},
		{"issue", "get"},
		{"issue", "events"},
		{"issue", "record"},
		{"issue", "context-risk"},
		{"issue", "get-many"},
		{"issue", "check"},
		{"issue", "doctor"},
		{"issue", "create"},
		{"issue", "split"},
		{"issue", "update"},
		{"issue", "close"},
		{"issue", "cleanup"},
		{"issue", "delete"},
		{"issue", "image"},
		{"issue", "image", "add"},
		{"issue", "image", "remove"},
		{"issue", "document"},
		{"issue", "document", "add"},
		{"issue", "document", "list"},
		{"issue", "document", "remove"},
		{"issue", "dep"},
		{"issue", "dep", "add"},
		{"issue", "dep", "remove"},
		{"issue", "dep", "bulk"},
		{"issue", "dep", "bulk", "apply"},
		{"issue", "bulk-create"},
		{"issue", "bulk-update"},
		{"issue", "fanout"},
		{"issue", "fanout", "ready"},
		{"issue", "fanout", "drift"},
		{"mail"},
		{"mail", "send"},
		{"mail", "list"},
		{"mail", "watch"},
		{"observe"},
		{"orchestrate"},
		{"orchestrate", "status"},
		{"orchestrate", "start"},
		{"orchestrate", "group"},
		{"orchestrate", "watch"},
		{"orchestrate", "observe"},
		{"orchestrate", "prompt"},
		{"orchestrate", "message"},
		{"orchestrate", "capture"},
		{"orchestrate", "complete-check"},
		{"orchestrate", "integrate"},
		{"orchestrate", "close-session"},
		{"daemon"},
		{"daemon", "start"},
		{"daemon", "stop"},
		{"daemon", "restart"},
		{"daemon", "watch-clients"},
	}

	for _, path := range paths {
		name := strings.Join(path, " ")
		if name == "" {
			name = "root"
		}
		t.Run(name, func(t *testing.T) {
			args := append([]string(nil), path...)
			args = append(args, "--help")
			output := captureMainStdout(t, func() error {
				if !maybePrintCommandHelp(args) {
					t.Fatalf("maybePrintCommandHelp(%v) = false, want true", args)
				}
				return nil
			})
			if !strings.Contains(strings.ToLower(output), "usage:") {
				t.Fatalf("help output missing usage line: %q", output)
			}
		})
	}
}
